### ISSUE TITLE
List of bots

### ISSUE THREAD

**Issue by milenavt** [Brandawg93/Botranks#8]
Hi Brandon,
I'm a [researcher at LSE](https://www.lse.ac.uk/Methodology/People/Academic-Staff/Milena-Tsvetkova/Milena-Tsvetkova) and I'm starting a project on human-bot interactions on Reddit. I came across Botranks before the Reddit API changes and thought it would be a great resource to get a list of all Reddit bots. Is there any chance you can send me these data? I mainly need the most complete list of bots you have, the rankings are less important (although I'm sure I'll be able to make use of that data too, if it is not too much trouble). I'd greatly appreciate your help and time. You can contact me at m.tsvetkova@lse.ac.uk.
Thanks, 
Milena

**Comment by Brandawg93** [comment]
I've reached out to your email!
